# A fazer
- inserir funções de custo
- corrigir falha da função de gerar pop.
 - quando não é uma matriz quadrada, ele reclama

In [87]:
import numpy as np
import random
import copy

## Funções

In [101]:
# Gerando pop. inicial

# N -> tamanho da pop. (TEM QUE SER MAIOR QUE 3)
# n -> quantidade de variáveis
# low -> limite inferior da distribuição uniforme
# high -> limite superior da distribuição uniforme
def init_pop(N:int, n:int, low:int, high:int):
    pop = np.zeros((1, N, n))
    for i in range (n):
        s = np.random.uniform(low, high, N)
        pop[0][i] = s
    return pop

# recebe a pop. e retorna 3 indivíduos (r1, r2, r3) -> cada um é um vetor unidimensional
def select_three(pop):
    rand_idxs = random.sample(range(0, pop.shape[1]), 3)
    return pop[:,rand_idxs[0]], pop[:,rand_idxs[1]], pop[:,rand_idxs[2]]

def evaluate(v):
    # dummy só para testar funcionamento     
    return np.sum(v)

## Alguns testes, só pra ver funcionando

In [116]:
a = init_pop(4,4,-2,2)
np.append(a, np.zeros((1 ,4, 4)), axis=0)

(array([ 0.74902749, -1.97593506, -1.02525026, -0.34161412]),
 array([-0.74561184,  1.92473953,  1.82930971,  1.11854067]),
 array([-0.44410435,  0.67229713, -1.13369888, -0.48744249]))

In [117]:
select_three(a[0])

(array([-1.26862244,  0.51278226,  1.06827535,  0.57661016]),
 array([-0.74561184,  1.92473953,  1.82930971,  1.11854067]),
 array([ 0.74902749, -1.97593506, -1.02525026, -0.34161412]))

## Parte que importa 

In [90]:
N = 5 
n = 5
low = -2
high = 2

# probabilidade de recombinacão. Sugestao: C ∈ [0.6, 0.9]
C = 0.6

# fator de escala. Sugestão F ∈ [0.7, 0.9]
F = 0.7

# inicializa pop.
pop = init_pop(N,n,low,high)

In [115]:
n_iter = 0

# enquanto crit. parada não satisfeito
while n_iter <= 10:
    
    # pega "camada mais recente" da pop.
    t_pop = copy.copy(pop[-1])
    
    # "mi" descrito no enunciado, solução mutante ("mais uma camada do bolo")
    solucao_mutante = np.zeros((N, n))
    
    new_layer = np.zeros((N, n))
    
    # iterando entre indivíduos
    for i in range(N):
        r1, r2, r3 = select_three(t_pop)
        sigma = random.randint(0, N)
        # iterando entre variáveis de um indivíduo
        for j in range(n):
            if np.random.uniform(0, 1) <= C or j == sigma:
                solucao_mutante[i][j] = r1[j] + F*(r2[j] - r3[j])
            else:
                solucao_mutante[i][j] = t_pop[i][j]
        
        # avaliamos o indivíduo e a solução mutante
        # se solução mutante for melhor, substitui-se o indivíduo original pela solução mutante
        if evaluate(solucao_mutante[:, i]) <= evaluate(t_pop[:, i]):
            new_layer[:, i] = solucao_mutante[:, i]
        else:
            new_layer[:, i] = t_pop[:, i]
    
    pop = np.concatenate((pop, [new_layer]), axis=0)        
    n_iter += 1