# A fazer
- inserir funções de custo
- corrigir falha da função de gerar pop.
 - quando não é uma matriz quadrada, ele reclama

In [1]:
import numpy as np
import random
import copy

## Funções

In [2]:
# Gerando pop. inicial

# N -> tamanho da pop. (TEM QUE SER MAIOR QUE 3)
# n -> quantidade de variáveis
# low -> limite inferior da distribuição uniforme
# high -> limite superior da distribuição uniforme
def init_pop(N:int, n:int, low:int, high:int):
    pop = np.zeros((1, N, n))
    for i in range (n):
        s = np.random.uniform(low, high, N)
        pop[0][i] = s
    return pop

# recebe a pop. e retorna 3 indivíduos (r1, r2, r3) -> cada um é um vetor unidimensional
def select_three(pop):
    rand_idxs = random.sample(range(0, pop.shape[1]), 3)
    return pop[:,rand_idxs[0]], pop[:,rand_idxs[1]], pop[:,rand_idxs[2]]

def evaluate(v):
    # dummy só para testar funcionamento     
    return np.sum(v)

## Alguns testes, só pra ver funcionando

In [3]:
a = init_pop(4,4,-2,2)
np.append(a, np.zeros((1 ,4, 4)), axis=0)

array([[[-1.50692977,  1.03115998,  1.9899985 ,  0.98743412],
        [-0.38072613,  1.39741899,  1.59544757,  1.09050877],
        [-1.62751451,  0.38779805,  1.82862504, -1.64767153],
        [-0.91493313, -1.59073373, -0.43643599, -0.35200918]],

       [[ 0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ]]])

In [4]:
select_three(a[0])

(array([-1.50692977, -0.38072613, -1.62751451, -0.91493313]),
 array([ 1.9899985 ,  1.59544757,  1.82862504, -0.43643599]),
 array([ 1.03115998,  1.39741899,  0.38779805, -1.59073373]))

## Parte que importa 

In [5]:
N = 5 
n = 5
low = -2
high = 2

# probabilidade de recombinacão. Sugestao: C ∈ [0.6, 0.9]
C = 0.6

# fator de escala. Sugestão F ∈ [0.7, 0.9]
F = 0.7

# inicializa pop.
pop = init_pop(N,n,low,high)

In [6]:
n_iter = 0

# enquanto crit. parada não satisfeito
while n_iter <= 30:
    
    print(f"iter: {n_iter}\n")
    
    # pega "camada mais recente" da pop.
    # t_pop = copy.copy(pop[-1])
    t_pop = pop[-1]

    # "mi" descrito no enunciado, solução mutante ("mais uma camada do bolo")
    solucao_mutante = np.zeros((N, n))
    
    new_layer = np.zeros((N, n))
    
    # iterando entre indivíduos
    for i in range(N):
        r1, r2, r3 = select_three(t_pop)
        sigma = random.randint(0, N)
        # iterando entre variáveis de um indivíduo
        for j in range(n):
            if np.random.uniform(0, 1) <= C or j == sigma:
                solucao_mutante[j][i] = r1[j] + F*(r2[j] - r3[j])
            else:
                solucao_mutante[j][i] = t_pop[j][i]
        
        print(f"solucao_mutante {i}:\n {solucao_mutante}\n")
        
        # avaliamos o indivíduo e a solução mutante
        # se solução mutante for melhor, substitui-se o indivíduo original pela solução mutante
        
        eval_mut = evaluate(solucao_mutante[:, i]) 
        eval_t_pop = evaluate(t_pop[:, i])
        
        print(f"eval_mut {i}:\n {eval_mut}\n")
        print(f"eval_tpop {i}:\n {eval_t_pop}\n")
        
        if eval_mut <= eval_t_pop:
            new_layer[:, i] = solucao_mutante[:, i]
        else:
            new_layer[:, i] = t_pop[:, i]
    
    print(f"new_layer:\n {new_layer}\n")

    pop = np.concatenate((pop, [new_layer]), axis=0)        
    n_iter += 1

iter: 0

solucao_mutante 0:
 [[ 1.68549034e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 1.39681361e-05  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 2.00893968e-01  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 5.12464375e-02  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [-1.05062923e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]]

eval_mut 0:
 0.8870154837569832

eval_tpop 0:
 0.9198211028737218

solucao_mutante 1:
 [[ 1.68549034e+00  1.57895340e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 1.39681361e-05  2.23426592e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 2.00893968e-01  1.66601377e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 5.12464375e-02 -2.64619418e-01  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [-1.05062923e+00  2.89241997e-01  0.00000000e+00  0.00000000e+00
   0.00000000e+00]]

eval_mut 1:
 5.503855662406435

In [7]:
pop[-1]

array([[-8.23077205, -8.23077205, -6.66325233, -8.23077205, -8.23077205],
       [-0.6288384 ,  0.3561832 , -2.30337511,  0.3561832 , -0.6288384 ],
       [-3.99837549, -4.67416213, -3.1614729 , -3.86151634, -3.86151634],
       [ 0.77161231,  1.41518808,  1.17183628,  1.08156939,  1.08156939],
       [-1.43276327, -1.43276327,  0.68522121,  0.68522121, -3.32404028]])